name = "content-os"
main = "src/index.js"
compatibility_date = "2025-06-19"
compatibility_flags = ["nodejs_compat"]

[vars]
# OAuth provider configuration
REDIRECT_URL = "https://content-os.echarris.workers.dev/callback"
